Repository Knect-Dev/Knect-Dev-Frontend, pull requests merged in 2022-03, with the labels that each got.

#15 Add PageHeader component
  src/components/PageHeader/PageHeader.css
  src/components/PageHeader/PageHeader.jsx
  src/pages/Stats/Stats.jsx
Labels: layout, front-end

#16 Search styling
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/theme/variables.css
Labels: layout, front-end

#17 EOD PR - Updates to Home page outline
  src/components/AddFAB.jsx
  src/components/JobsList/JobsList.jsx
  src/components/JobsList/jobsList.scss
  src/pages/Home/Home.jsx
Labels: layout, front-end

#20 Profile header
  src/pages/Profile/Profile.jsx
Labels: layout, front-end

#28 Add basic redux scaffolding for all models
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header/Header.jsx
  src/components/JobsList/JobsList.jsx
  src/components/Menu.jsx
  src/store/companies.js
  src/store/contacts.js
  src/store/index.js
  src/store/jobs.js
  src/store/user.js
Labels: front-end

#29 Slide
  src/App.jsx
  src/components/Header/Header.jsx
Labels: layout, front-end

#30 Adds Jobslist to resolve Issue #14
  src/App.jsx
  src/components/JobItems/JobItem.jsx
  src/components/JobItems/jobItem.scss
  src/components/JobsList/JobsList.jsx
  src/components/JobsList/jobsList.scss
  src/components/Profile/ProfileContainer.jsx
  src/pages/Home/Home.jsx
Labels: layout, front-end

#35 Adds basic get request functionality
  src/components/ParentForm/Company/CompanyForm.jsx
  src/store/companies.js
Labels: front-end

#36 Debugs list props
  src/components/JobItems/JobItem.jsx
  src/components/JobsList/JobsList.jsx
Labels: front-end

#37 Add basica styling to profile page
  src/components/Profile/ProfileContainer.jsx
  src/components/StatCard/StatCard.jsx
  src/pages/Profile/Profile.jsx
Labels: layout, front-end

#38 Filter menu
  src/App.jsx
  src/components/Filter/Filter.jsx
  src/components/Header/Header.jsx
  src/components/JobsList/JobsList.jsx
  src/pages/Home/Home.jsx
  src/store/currentPage.js
  src/store/index.js
Labels: layout, front-end

#39 Move modal close to top bar
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/Job/jobForm.scss
  src/components/ParentForm/ParentForm.jsx
  src/pages/Profile/Profile.jsx
Labels: help wanted, front-end

#43 re-adds company retrieval from DB
  src/store/companies.js
  src/store/jobs.js
Labels: layout, front-end

#44 Add logout button to header, no functionality
  src/components/Header/Header.jsx
  src/components/Header/header.scss
  src/components/ParentForm/Company/CompanyForm.jsx
Labels: layout, front-end

#46 Adds fuzzysort to search bar, styles jobs list, resolves issue #32
  package-lock.json
  package.json
  src/components/Header/Header.jsx
  src/components/JobItems/JobItem.jsx
  src/components/JobsList/JobsList.jsx
  src/components/JobsList/jobsList.scss
  src/pages/Home/Home.jsx
  src/store/index.js
  src/store/jobs.js
  src/store/search.js
Labels: enhancement, front-end

#48 Login
  src/App.jsx
  src/components/Auth/Auth.jsx
  src/components/Auth/SignIn.jsx
  src/components/Auth/SignUp.jsx
  src/store/user.js
Labels: enhancement

#49 breaks App into App and Main components to allow for conditional rend…
  src/App.jsx
  src/Main.jsx
Labels: enhancement, front-end

#50 Signup
  src/components/Auth/SignIn.jsx
  src/components/Auth/SignUp.jsx
  src/store/user.js
Labels: enhancement, front-end

#52 updates axios dispatch calls to use user state token
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/pages/Home/Home.jsx
  src/store/companies.js
  src/store/jobs.js
Labels: enhancement, front-end

#53 updates profile form to render user data
  src/components/Profile/ProfileContainer.jsx
Labels: front-end

#54 Logout session
  package-lock.json
  package.json
  src/Main.jsx
  src/components/Header/Header.jsx
  src/store/user.js
Labels: front-end

#59 Job delete alert
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Company/companyForm.scss
  src/components/ParentForm/Contact/ContactForm.jsx
  src/components/ParentForm/Contact/contactForm.scss
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/Job/jobForm.scss
Labels: enhancement, front-end

#60 Logout session
  package-lock.json
  package.json
  src/Main.jsx
  src/store/user.js
Labels: front-end

#63 Form stage
  src/components/JobItems/JobItem.jsx
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Contact/ContactForm.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/Job/jobForm.scss
Labels: enhancement

#65 add stand in graph data
  src/components/BarGraph/BarGraph.jsx
  src/components/XYGrid/XYGrid.jsx
  src/pages/Stats/Stats.jsx
Labels: front-end

#66 Sort companies
  src/components/CompanySelector/CompanySelector.jsx
  src/components/ParentForm/Job/JobForm.jsx
Labels: layout, front-end

#67 removed unused variables and console logs
  src/components/Auth/SignIn.jsx
  src/components/Auth/SignUp.jsx
  src/components/CompanySelector/CompanySelector.jsx
  src/components/Filter/Filter.jsx
  src/components/Header/Header.jsx
  src/components/JobItems/JobItem.jsx
  src/components/JobsList/JobsList.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/ParentForm.jsx
  src/components/Profile/ProfileContainer.jsx
  src/pages/Home/Home.jsx
  src/store/companies.js
  src/store/currentPage.js
  src/store/jobs.js
  src/store/user.js
Labels: front-end

#68 Cant find company
  src/components/CompanySelector/CompanySelector.jsx
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Contact/ContactForm.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/ParentForm.jsx
Labels: enhancement, front-end

#70 able to add new companies into database, and edit company information
  src/components/ParentForm/Company/CompanyForm.jsx
Labels: enhancement, front-end

#72 Add logo and styling for stats
  public/assets/icon/Knect.dev.png:Zone.Identifier
  public/assets/icon/knect_dev.png
  public/index.html
  src/components/Auth/Auth.jsx
  src/components/Auth/SignIn.jsx
  src/components/Auth/SignUp.jsx
  src/components/BarGraph/BarGraph.jsx
  src/components/Profile/ProfileContainer.jsx
  src/pages/Stats/Stats.jsx
  src/resources/Knect.dev.bmp
  src/resources/Knect.dev.png
  src/resources/knect_small.png
Labels: front-end

#73 add conditional rendering for logout button
  src/Main.jsx
  src/components/Header/Header.jsx
Labels: front-end

#74 adds redirects file
  public/_redirects
  src/components/Header/Header.jsx
Labels: enhancement, front-end

#75 UI Fix on Form VERY MINOR
  src/components/CompanySelector/CompanySelector.jsx
Labels: enhancement, front-end

#76 Trash button
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/ParentForm.jsx
  src/components/TrashButton/TrashButton.jsx
  src/store/jobs.js
Labels: bug, enhancement, front-end

#81 Rerender fix
  src/components/ParentForm/Job/JobForm.jsx
  src/pages/Home/Home.jsx
  src/store/jobs.js
Labels: bug, enhancement

#86 Blank form
  src/components/AddFab/AddFAB.jsx
  src/components/CompanySelector/CompanySelector.jsx
  src/components/JobItems/JobItem.jsx
  src/components/JobItems/jobItem.scss
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/Job/jobForm.scss
  src/components/ParentForm/ParentForm.jsx
  src/components/TrashButton/TrashButton.jsx
  src/pages/Home/Home.jsx
  src/resources/knect_dev_white.png
Labels: enhancement, front-end, form

#92 Add check to stop filter and search from rendering after logout
  src/components/Header/Header.jsx
  src/components/ParentForm/Company/CompanyForm.jsx
Labels: front-end

#93 Modify styling of login/auth page to be reactive for mobile
  src/components/Auth/Auth.jsx
  src/components/Auth/SignIn.jsx
  src/components/Auth/SignUp.jsx
Labels: front-end

#94 Modify styling of profile page to be reactive for mobile
  src/components/Auth/Auth.jsx
  src/components/Profile/ProfileContainer.jsx
  src/pages/Profile/Profile.jsx
Labels: front-end

#95 UI fixes
  src/components/LockButton/LockButton.jsx
  src/components/LockButton/lockButton.scss
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Job/JobForm.jsx
  src/components/ParentForm/Job/jobForm.scss
  src/components/ParentForm/ParentForm.jsx
  src/components/ParentForm/ParentForm.scss
  src/store/companies.js
Labels: enhancement, front-end, form

#96 fixes small bug with closing of contact form
  src/components/ParentForm/Company/CompanyForm.jsx
  src/components/ParentForm/Contact/ContactForm.jsx
  src/components/ParentForm/ParentForm.jsx
  src/components/ParentForm/ParentForm.scss
Labels: bug, form

#100 change darkmode bg color in theme
  src/theme/variables.css
Labels: front-end
